version: "3"

services:

  luminesce-sdk-extensions-csharp-test:
    build: .
    container_name: luminesce-sdk-extensions-csharp-test
    image: finbourne/luminesce-sdk-extensions-csharp-test
    environment:
      - FBN_TOKEN_URL
      - FBN_USERNAME
      - FBN_PASSWORD
      - FBN_CLIENT_ID
      - FBN_CLIENT_SECRET
      - FBN_LUMINESCE_API_URL
      - FBN_APP_NAME
    volumes:
      - .:/usr/src